server:
    port: 8080

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://mysql/homedb?autoReconnect=true&useSSL=false
        username: root
        password: root123
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5