server:
    port: 8080

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://${DB_HOST}/${DB_NAME}?autoReconnect=true&useSSL=false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5